In [ ]:
# K-means clustering (10 points) Perform K-Means with K=3 using and report:  
# • Initialization method used and initial centroid for each cluster 
# • Number of iterations until convergence 
# • Final centroids 1 
# • Cluster variances (within-cluster sum of squares) 
# • Number of samples assigned to each cluster 

import pandas as pd
from sklearn.cluster import KMeans
import numpy as np

df = pd.read_csv('StdGasProperties.csv').drop(columns=['Idx'])

# need to get initial centroid
kmeans_init = KMeans(n_clusters=3, random_state=0, n_init=1, max_iter=1)
kmeans_init.fit(df)

# initial centroids
initial_centroids = kmeans_init.cluster_centers_
print("Initial centroids:")
print(initial_centroids)

kmeans = KMeans(n_clusters = 3, random_state=0, n_init="auto")
kmeans.fit(df)
# Final centroids: cluster_centers_
final_centroids = kmeans.cluster_centers_
print("Final centroids: ")
print(final_centroids)

# num of iterations: n_iter_
num_iter = kmeans.n_iter_
print("Num iterations: ")
print(num_iter)

# Within-cluser sum of squares: inertia_
within_cluster_sum_squares = kmeans.inertia_
print("Within-cluster sum of squares: ", within_cluster_sum_squares)
# Samples per Cluster: labels
labels = kmeans.labels_
sample_counts = np.bincount(labels)
print("Samples per Cluster: ", sample_counts)

Initial centroids:
[[ 1.2676356   0.26645508  1.28022968  1.09196791]
 [-0.90785779  0.2454467  -0.73956444 -0.93340861]
 [ 0.31206019 -0.59818322  0.045386    0.4991046 ]]
Final centroids:  [[ 1.1020497   0.41490904  1.14272492  0.8899065 ]
 [-1.02022642  0.17459572 -0.84854502 -1.01766398]
 [ 0.23514467 -0.69770102 -0.0507657   0.462647  ]]
Final centroids:  [[ 1.1020497   0.41490904  1.14272492  0.8899065 ]
 [-1.02022642  0.17459572 -0.84854502 -1.01766398]
 [ 0.23514467 -0.69770102 -0.0507657   0.462647  ]]
Num iterations:  7
Within-cluster sum of squares:  655063.8645185288
Samples per Cluster:  [130784 169226 119990]
