# Project 1, CPSC 585
## Authors: Brian Chu (brianmchu42@csu.fullerton.edu), [put your name and email here]

### 1. Clustering (70 points)

#### Data preparation and preprocessing (5 points)
Standardize (z-score scaling) the four chemical properties and save them in a file named
“StdGasProperties.csv”, which will be used for the remaining tasks. Briefly explain:
* The importance of data standardization
* Feature mean and standard deviation before and after standardization

Clustering must be performed using only the four chemical features (excluding idx).

In [17]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer

df = pd.read_csv("GasProperties.csv")

# skip Idx and only scale the four chemical properties
props = ['T', 'P', 'TC', 'SV']
idx = ['Idx']

preprocessor = ColumnTransformer(
    transformers = [
        ('scaler', StandardScaler(), props),
    ],
    remainder = 'passthrough'
)

transformed = preprocessor.fit_transform(df)

transformed_df = pd.DataFrame(transformed, columns = props + idx)

print('### ORIGINAL ###')
print(df)

print('### MEAN ###')
print(df.mean())
print('### STD ###')
print(df.std())

print('### TRANSFORMED ###')
print(transformed_df)

print('### MEAN ### ')
print(transformed_df.mean())
print('### STD ###')
print(transformed_df.std())

transformed_df.to_csv('StdGasProperties.csv', index=False)

### ORIGINAL ###
             T      P        TC          SV        Idx
0       253.15   17.7  0.026827  389.355242  54.102967
1       253.15   17.7  0.026970  388.007160  54.162740
2       253.15   17.7  0.026912  385.677846  54.232917
3       253.15   17.7  0.026815  384.292031  54.304434
4       253.15   17.7  0.026731  392.060606  54.070973
...        ...    ...       ...         ...        ...
419995  353.15  300.0  0.041824  435.341910  53.755453
419996  353.15  300.0  0.041518  426.840370  54.234870
419997  353.15  300.0  0.041744  428.069807  54.106685
419998  353.15  300.0  0.041607  430.308699  53.970731
419999  353.15  300.0  0.041669  432.137751  54.077029

[420000 rows x 5 columns]
### MEAN ###
T      303.150000
P      121.100000
TC       0.034696
SV     415.243807
Idx     53.972392
dtype: float64
### STD ###
T      34.156543
P      95.286764
TC      0.004071
SV     22.532554
Idx     0.251821
dtype: float64
### TRANSFORMED ###
              T         P        TC        SV 

Data standardization is important to regularize the data - numbers that are large in magnitude can be harder to process with some models. For example, since the magnitude of the `T` and `SV` columns in the data are more than two orders of magnitude larger than the `P` and `TC` columns, the `T` and `SV` columns can have an outsize effect on model predictions. Regularizing ensures that all relevant features are considered equally by the model.

As seen in the printout of the data, the original data has some particular mean and standard deviation, but when regularized, the mean becomes 0 and the standard deviation 1 (mathematically, with some floating point rounding error in practice)

#### K-means clustering (10 points)
Perform K-Means with K=3 using and report:
* Initialization method used and initial centroid for each cluster
* Number of iterations until convergence
* Final centroids
* Cluster variances (within-cluster sum of squares)
* Number of samples assigned to each cluster

In [37]:
from sklearn.cluster import KMeans
from collections import Counter

cluster = KMeans(n_clusters=3, random_state=42)
cluster.fit(transformed_df)

print('Iterations before convergence: ', cluster.n_iter_)
print('Final centroids: ', cluster.cluster_centers_)
print('Samples per cluster: ', Counter(cluster.labels_))


6
[[ 0.92062126 -0.11341908  0.81435343  0.89984168 53.96808213]
 [-0.63049058  1.20625088 -0.09642652 -0.95724181 53.98892158]
 [-0.92012503 -0.63792426 -1.12098841 -0.67236797 53.96766187]]
Counter({np.int32(0): 195964, np.int32(2): 134691, np.int32(1): 89345})


#### EM clustering (15 points)
Fit a Gaussian Mixture Model (GMM) with K=3 for clustering and report:
* Initialization method and initial parameters
* Convergence criterion (tolerance or max iterations)
* Covariance type (full, diagonal, spherical) with justification
* Mixture weights (𝜋_𝑘), means (𝜇_𝑘), covariances (Σ_𝑘) for each cluster
* For 3 samples, show probabilities 𝑝(𝑧 = 𝑘|𝑥)

In [ ]:
from sklearn.mixture import GaussianMixture

gauss = GaussianMixture(n_components=3)

gauss.fit(transformed_df)
